//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Library.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terug.
        /// </summary>
        public static string Action_Back {
            get {
                return ResourceManager.GetString("Action_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuleren.
        /// </summary>
        public static string Action_Cancel {
            get {
                return ResourceManager.GetString("Action_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kies.
        /// </summary>
        public static string Action_Choose {
            get {
                return ResourceManager.GetString("Action_Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieuw.
        /// </summary>
        public static string Action_Create {
            get {
                return ResourceManager.GetString("Action_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bezig met laden.....
        /// </summary>
        public static string Action_Loading {
            get {
                return ResourceManager.GetString("Action_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volgende.
        /// </summary>
        public static string Action_Next {
            get {
                return ResourceManager.GetString("Action_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorige.
        /// </summary>
        public static string Action_Previous {
            get {
                return ResourceManager.GetString("Action_Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opslaan.
        /// </summary>
        public static string Action_Save {
            get {
                return ResourceManager.GetString("Action_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoeken.
        /// </summary>
        public static string Action_Search {
            get {
                return ResourceManager.GetString("Action_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bewerken.
        /// </summary>
        public static string Action_Update {
            get {
                return ResourceManager.GetString("Action_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auteur.
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voornamen.
        /// </summary>
        public static string Author_FirstNames {
            get {
                return ResourceManager.GetString("Author_FirstNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volledige naam.
        /// </summary>
        public static string Author_FullName {
            get {
                return ResourceManager.GetString("Author_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialen.
        /// </summary>
        public static string Author_Initials {
            get {
                return ResourceManager.GetString("Author_Initials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achternaam.
        /// </summary>
        public static string Author_LastName {
            get {
                return ResourceManager.GetString("Author_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tussenvoegsel.
        /// </summary>
        public static string Author_Prefix {
            get {
                return ResourceManager.GetString("Author_Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auteurs.
        /// </summary>
        public static string Authors {
            get {
                return ResourceManager.GetString("Authors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boek.
        /// </summary>
        public static string Book {
            get {
                return ResourceManager.GetString("Book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternatieve titel.
        /// </summary>
        public static string Book_AlternativeTitle {
            get {
                return ResourceManager.GetString("Book_AlternativeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auteur.
        /// </summary>
        public static string Book_Author {
            get {
                return ResourceManager.GetString("Book_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISBN.
        /// </summary>
        public static string Book_Isbn {
            get {
                return ResourceManager.GetString("Book_Isbn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is een serie.
        /// </summary>
        public static string Book_IsBookGroup {
            get {
                return ResourceManager.GetString("Book_IsBookGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titel.
        /// </summary>
        public static string Book_Title {
            get {
                return ResourceManager.GetString("Book_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre.
        /// </summary>
        public static string BookGenre {
            get {
                return ResourceManager.GetString("BookGenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serie.
        /// </summary>
        public static string BookGroup {
            get {
                return ResourceManager.GetString("BookGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er zijn 0 resultaten gevonden. Verander uw zoekopdracht of voeg onderstaand de serie toe..
        /// </summary>
        public static string BookGroup_Create_Warning {
            get {
                return ResourceManager.GetString("BookGroup_Create_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naam serie.
        /// </summary>
        public static string BookGroup_Name {
            get {
                return ResourceManager.GetString("BookGroup_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boeken.
        /// </summary>
        public static string Books {
            get {
                return ResourceManager.GetString("Books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoek op basis van serienaam, boektitel en/of auteur naar een serie..
        /// </summary>
        public static string Component_BookGroupSearch_SearchText {
            get {
                return ResourceManager.GetString("Component_BookGroupSearch_SearchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} toevoegen.
        /// </summary>
        public static string Format_Add {
            get {
                return ResourceManager.GetString("Format_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welkom.
        /// </summary>
        public static string Global_Welcome {
            get {
                return ResourceManager.GetString("Global_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open mijn boeken.
        /// </summary>
        public static string GoTo_Person_OwnedBooks {
            get {
                return ResourceManager.GetString("GoTo_Person_OwnedBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open mijn wensenlijst.
        /// </summary>
        public static string GoTo_Person_WishListBooks {
            get {
                return ResourceManager.GetString("GoTo_Person_WishListBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mijn boeken.
        /// </summary>
        public static string Person_OwnedBooks {
            get {
                return ResourceManager.GetString("Person_OwnedBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mijn wensenlijst voor boeken.
        /// </summary>
        public static string Person_WishListBooks {
            get {
                return ResourceManager.GetString("Person_WishListBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auteur (Voornaam / Achternaam).
        /// </summary>
        public static string SearchBookGroupRequest_Author {
            get {
                return ResourceManager.GetString("SearchBookGroupRequest_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vul 1 van de onderstaande velden in met minimaal 2 karakters..
        /// </summary>
        public static string SearchBookGroupRequest_RequiredMessage {
            get {
                return ResourceManager.GetString("SearchBookGroupRequest_RequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoekresultaten.
        /// </summary>
        public static string SearchResults {
            get {
                return ResourceManager.GetString("SearchResults", resourceCulture);
            }
        }
    }
}
