//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library.Domain.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DomainResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DomainResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Library.Domain.Properties.DomainResources", typeof(DomainResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gebruiker.
        /// </summary>
        public static string ApplicationUser {
            get {
                return ResourceManager.GetString("ApplicationUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emailadres.
        /// </summary>
        public static string ApplicationUser_Email {
            get {
                return ResourceManager.GetString("ApplicationUser_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wachtwoord.
        /// </summary>
        public static string ApplicationUser_Password {
            get {
                return ResourceManager.GetString("ApplicationUser_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bevestig wachtwoord.
        /// </summary>
        public static string ApplicationUser_PasswordConfirmation {
            get {
                return ResourceManager.GetString("ApplicationUser_PasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefoonnummer.
        /// </summary>
        public static string ApplicationUser_PhoneNumber {
            get {
                return ResourceManager.GetString("ApplicationUser_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gebruikersnaam.
        /// </summary>
        public static string ApplicationUser_UserName {
            get {
                return ResourceManager.GetString("ApplicationUser_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gebruikers.
        /// </summary>
        public static string ApplicationUsers {
            get {
                return ResourceManager.GetString("ApplicationUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boek.
        /// </summary>
        public static string Book {
            get {
                return ResourceManager.GetString("Book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toevoegen aan mijn boeken.
        /// </summary>
        public static string Book_AddToMyBooks {
            get {
                return ResourceManager.GetString("Book_AddToMyBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toevoegen aan wensenlijst.
        /// </summary>
        public static string Book_AddToWishlist {
            get {
                return ResourceManager.GetString("Book_AddToWishlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auteur.
        /// </summary>
        public static string Book_Author {
            get {
                return ResourceManager.GetString("Book_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISBN.
        /// </summary>
        public static string Book_Isbn {
            get {
                return ResourceManager.GetString("Book_Isbn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titel.
        /// </summary>
        public static string Book_Title {
            get {
                return ResourceManager.GetString("Book_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bevestig uw account door &lt;a href=&apos;{0}&apos;&gt;hier te klikken&lt;/a&gt;..
        /// </summary>
        public static string MailService_Mail_ApplicationUserConfirmEmail {
            get {
                return ResourceManager.GetString("MailService_Mail_ApplicationUserConfirmEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bevestig uw emailadres.
        /// </summary>
        public static string MailService_Subject_ApplicationUserConfirmEmail {
            get {
                return ResourceManager.GetString("MailService_Subject_ApplicationUserConfirmEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieuwsbericht.
        /// </summary>
        public static string NewsMessage {
            get {
                return ResourceManager.GetString("NewsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tonen in overzicht.
        /// </summary>
        public static string NewsMessage_IsShown {
            get {
                return ResourceManager.GetString("NewsMessage_IsShown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bericht.
        /// </summary>
        public static string NewsMessage_Message {
            get {
                return ResourceManager.GetString("NewsMessage_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titel.
        /// </summary>
        public static string NewsMessage_Title {
            get {
                return ResourceManager.GetString("NewsMessage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieuwsberichten.
        /// </summary>
        public static string NewsMessages {
            get {
                return ResourceManager.GetString("NewsMessages", resourceCulture);
            }
        }
    }
}
